services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trabalho-final-db
    ports:
      - "5433:5432"
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
